services:
  _defaults:
    autowire: true
    autoconfigure: true

  App\User\Application\EventListener\OnBottleCreatedCheckIfOwnerExistEventListener:
    tags: [kernel.event_listener]

  App\User\Application\EventListener\OnBottleAddedPictureCheckIfUserIsAuthorizeToUpdateBottleEventListener:
    tags: [kernel.event_listener]
