parameters:

services:
  _defaults:
    autowire: true
    autoconfigure: true
    bind:
      $kernelProjectDirectory: '%kernel.project_dir%'

  App\:
    resource: '../../src/'
    exclude:
      - '../../src/Bottle/'
      - '../../src/User/'

  App\Bottle\Application\EventListener\OnOwnerNotExistEventListener:
    tags: [kernel.event_listener]

  App\Bottle\Application\EventListener\OnBottleUpdatedNotAuthorizeEventListener:
    tags: [kernel.event_listener]

  App\Bottle\Application\EventListener\OnBottleDeletedNotAuthorizeEventListener:
    tags: [kernel.event_listener]

  App\Bottle\Infrastructure\Country\Http\Client\CountryHttpClientInterface:
    alias: App\Bottle\Infrastructure\Country\Http\Client\CountryHttpClient

  App\Bottle\Domain\Service\UploadBottlePictureServiceInterface:
    alias: App\Bottle\Infrastructure\VichUploader\UploadBottlePictureVichUploaderService

when@test:
  services:
    App\Bottle\Infrastructure\Country\Http\Client\CountryHttpClientInterface:
      alias: App\Bottle\Infrastructure\Country\Http\Client\CountryFakeHttpClient

    App\Bottle\Domain\Service\UploadBottlePictureServiceInterface:
      alias: App\Bottle\Infrastructure\VichUploader\UploadBottlePictureVichUploaderTestService
