parameters:

services:
  _defaults:
    autowire: true
    autoconfigure: true
    bind:
      $kernelProjectDirectory: '%kernel.project_dir%'

  App\:
    resource: '../../src/'
    exclude:
      - '../../src/Country/'
      - '../../src/Tasting/'
      - '../../src/Security/'

  App\BottleInventory\Application\EventListener\OnBottleTasted:
    tags: [kernel.event_listener]

  App\BottleInventory\Infrastructure\Country\Repository\CountryRepositoryInterface:
    alias: App\BottleInventory\Infrastructure\Country\Repository\CountryRepository

  App\BottleInventory\Infrastructure\Security\Repository\UserRepositoryInterface:
    alias: App\BottleInventory\Infrastructure\Security\Repository\UserRepository

  App\BottleInventory\Domain\Service\UploadBottlePictureInterface:
    alias: App\BottleInventory\Infrastructure\VichUploader\UploadBottlePictureVichUploader

when@test:
  services:
    App\BottleInventory\Infrastructure\Country\Repository\CountryRepositoryInterface:
      alias: App\BottleInventory\Infrastructure\Country\Repository\CountryFakeRepository

    App\BottleInventory\Infrastructure\Security\Repository\UserRepositoryInterface:
      alias: App\BottleInventory\Infrastructure\Security\Repository\UserFakeRepository

    App\BottleInventory\Domain\Service\UploadBottlePictureInterface:
      alias: App\BottleInventory\Infrastructure\VichUploader\UploadBottlePictureVichUploaderFake
