parameters:

services:
  _defaults:
    autowire: true
    autoconfigure: true
    bind:
      $kernelProjectDirectory: '%kernel.project_dir%'

  App\:
    resource: '../../src/'
    exclude:
      - '../../src/Country/'
      - '../../src/Security/'

  App\BottleInventory\Application\EventListener\OnOwnerNotExistEventListener:
    tags: [kernel.event_listener]

  App\BottleInventory\Application\EventListener\OnBottleUpdatedNotAuthorizeEventListener:
    tags: [kernel.event_listener]

  App\BottleInventory\Application\EventListener\OnBottleDeletedNotAuthorizeEventListener:
    tags: [kernel.event_listener]

  App\BottleInventory\Infrastructure\Country\Http\Client\CountryHttpClientInterface:
    alias: App\BottleInventory\Infrastructure\Country\Http\Client\CountryHttpClient

  App\BottleInventory\Domain\Service\UploadBottlePictureServiceInterface:
    alias: App\BottleInventory\Infrastructure\VichUploader\UploadBottlePictureVichUploaderService

when@test:
  services:
    App\BottleInventory\Infrastructure\Country\Http\Client\CountryHttpClientInterface:
      alias: App\BottleInventory\Infrastructure\Country\Http\Client\CountryFakeHttpClient

    App\BottleInventory\Domain\Service\UploadBottlePictureServiceInterface:
      alias: App\BottleInventory\Infrastructure\VichUploader\UploadBottlePictureVichUploaderTestService
