parameters:

services:
  _defaults:
    autowire: true
    autoconfigure: true
    bind:
      $kernelProjectDirectory: '%kernel.project_dir%'

  App\:
    resource: '../../src/'
    exclude:
      - '../../src/BottleInventory/'
      - '../../src/Security/'