parameters:

services:
  _defaults:
    autowire: true
    autoconfigure: true
    bind:
      $kernelProjectDirectory: '%kernel.project_dir%'
      $emailTastingUserService: '%env(SERVICE_ACCOUNT_TASTING_LOGIN)%'
      $passwordTastingUserService: '%env(SERVICE_ACCOUNT_TASTING_PASSWORD)%'

  App\:
    resource: '../../src/'
    exclude:
      - '../../src/BottleInventory/'
      - '../../src/Country/'
      - '../../src/Security/'

  App\Tasting\Infrastructure\Security\Http\Client\UserHttpClientInterface:
    alias: App\Tasting\Infrastructure\Security\Http\Client\UserHttpClient

  App\Tasting\Application\Service\NotificationInterface:
    alias: App\Tasting\Infrastructure\Firebase\NotificationFirebase
    public: true

when@test:
  services:
    App\Tasting\Infrastructure\Security\Http\Client\UserHttpClientInterface:
      alias: App\Tasting\Infrastructure\Security\Http\Client\UserFakeHttpClient

    App\Tasting\Application\Service\NotificationInterface:
      alias: App\Tasting\Infrastructure\Firebase\NotificationFirebaseFake
      public: true