parameters:

services:
  _defaults:
    autowire: true
    autoconfigure: true
    bind:
      $kernelProjectDirectory: '%kernel.project_dir%'
      $emailTastingUserService: '%env(SERVICE_ACCOUNT_TASTING_LOGIN)%'
      $passwordTastingUserService: '%env(SERVICE_ACCOUNT_TASTING_PASSWORD)%'

  App\:
    resource: '../../src/'
    exclude:
      - '../../src/BottleInventory/'
      - '../../src/Country/'
      - '../../src/Security/'

  App\Tasting\Infrastructure\Security\Repository\UserRepositoryInterface:
    alias: App\Tasting\Infrastructure\Security\Repository\UserRepository

  App\Tasting\Application\Service\NotificationInterface:
    alias: App\Tasting\Infrastructure\Firebase\NotificationFirebase
    public: true

when@test:
  services:
    App\Tasting\Infrastructure\Security\Repository\UserRepositoryInterface:
      alias: App\Tasting\Infrastructure\Security\Repository\UserFakeRepository

    App\Tasting\Application\Service\NotificationInterface:
      alias: App\Tasting\Infrastructure\Firebase\NotificationFirebaseFake
      public: true