parameters:

services:
  _defaults:
    autowire: true
    autoconfigure: true
    bind:
      $kernelProjectDirectory: '%kernel.project_dir%'

  App\:
    resource: '../../src/'
    exclude:
      - '../../src/Country/'

  App\Security\Domain\Service\AuthenticateUserInterface:
    alias: App\Security\Infrastructure\Firebase\Security\Authenticator\AuthenticateUserFirebase

  App\Security\Application\EventListener\OnBottleCreatedCheckIfOwnerExistEventListener:
    tags: [kernel.event_listener]

  App\Security\Application\EventListener\OnBottleAddedPictureCheckIfUserIsAuthorizeToUpdateBottleEventListener:
    tags: [kernel.event_listener]

  App\Security\Application\EventListener\OnBottleDeletedCheckIfUserIsAuthorizeToDeleteBottleEventListener:
    tags: [kernel.event_listener]

  App\Security\Application\EventListener\OnBottleUpdatedCheckIfUserIsAuthorizeToUpdateBottleEventListener:
    tags: [kernel.event_listener]

  App\BottleInventory\Application\EventListener\OnOwnerNotExistEventListener:
    tags: [kernel.event_listener]

  App\BottleInventory\Application\EventListener\OnBottleUpdatedNotAuthorizeEventListener:
    tags: [kernel.event_listener]

  App\BottleInventory\Application\EventListener\OnBottleDeletedNotAuthorizeEventListener:
    tags: [kernel.event_listener]

when@test:
  services:
    App\Security\Domain\Service\AuthenticateUserInterface:
      alias: App\Security\Infrastructure\Firebase\Security\Authenticator\AuthenticateUserFakeFirebase