parameters:

services:
  _defaults:
    autowire: true
    autoconfigure: true
    bind:
      $kernelProjectDirectory: '%kernel.project_dir%'
      $emailBottleInventoryUserService: '%env(SERVICE_ACCOUNT_BOTTLE_INVENTORY_LOGIN)%'
      $passwordBottleInventoryUserService: '%env(SERVICE_ACCOUNT_BOTTLE_INVENTORY_PASSWORD)%'

  App\:
    resource: '../../src/'
    exclude:
      - '../../src/Country/'
      - '../../src/Tasting/'

  App\Security\Domain\Service\AuthenticateUserInterface:
    alias: App\Security\Infrastructure\Firebase\Security\Authenticator\AuthenticateUserFirebase

  App\Security\Domain\Service\LogInInterface:
    alias: App\Security\Infrastructure\Firebase\Security\LogIn\LogInFirebase

  App\BottleInventory\Application\EventListener\OnBottleTasted:
    tags: [kernel.event_listener]

  App\Tasting\Application\EventListener\OnInvitationCreated:
    tags: [kernel.event_listener]

  App\Tasting\Application\EventListener\OnInvitationAccepted:
    tags: [kernel.event_listener]

  App\Tasting\Application\EventListener\OnInvitationRejected:
    tags: [kernel.event_listener]

  App\Security\Application\EventListener\OnUserCreated:
    tags: [kernel.event_listener]

when@dev:
  services:
    App\Security\Domain\Service\AuthenticateUserInterface:
      alias: App\Security\Infrastructure\Firebase\Security\Authenticator\AuthenticateUserFakeFirebase

when@test:
  services:
    App\Security\Domain\Service\AuthenticateUserInterface:
      alias: App\Security\Infrastructure\Firebase\Security\Authenticator\AuthenticateUserFakeFirebase

    App\Security\Domain\Service\LogInInterface:
      alias: App\Security\Infrastructure\Firebase\Security\LogIn\LogInFakeFirebase