parameters:

services:
  _defaults:
    autowire: true
    autoconfigure: true
    bind:
      $kernelProjectDirectory: '%kernel.project_dir%'

  App\:
    resource: '../../src/'
    exclude:
      - '../../src/Country/'

  App\Security\Domain\Service\AuthenticateUserInterface:
    alias: App\Security\Infrastructure\Firebase\Security\Authenticator\AuthenticateUserFirebase

  App\BottleInventory\Application\EventListener\OnBottleTastedEventListener:
    tags: [kernel.event_listener]

  App\Security\Application\EventListener\OnUserCreatedEventListener:
    tags: [kernel.event_listener]

when@test:
  services:
    App\Security\Domain\Service\AuthenticateUserInterface:
      alias: App\Security\Infrastructure\Firebase\Security\Authenticator\AuthenticateUserFakeFirebase