services:
  _defaults:
    autowire: true
    autoconfigure: true

  App\Bottle\Application\EventListener\OnOwnerNotExistEventListener:
    tags: [kernel.event_listener]

  App\Bottle\Application\EventListener\OnBottleUpdatedNotAuthorizeEventListener:
    tags: [kernel.event_listener]

  App\Bottle\Application\EventListener\OnBottleDeletedNotAuthorizeEventListener:
    tags: [kernel.event_listener]