parameters:

services:
  _defaults:
    autowire: true
    autoconfigure: true
    bind:
      $kernelProjectDirectory: '%kernel.project_dir%'

  App\:
    resource: '../../src/'
    exclude:
      - '../../src/Bottle/'
      - '../../src/Country/'

  App\User\Domain\Service\AuthenticateUserInterface:
    alias: App\User\Infrastructure\Firebase\Security\Authenticator\AuthenticateUserFirebase

  App\User\Application\EventListener\OnBottleCreatedCheckIfOwnerExistEventListener:
    tags: [kernel.event_listener]

  App\User\Application\EventListener\OnBottleAddedPictureCheckIfUserIsAuthorizeToUpdateBottleEventListener:
    tags: [kernel.event_listener]

when@test:
  services:
    App\User\Domain\Service\AuthenticateUserInterface:
      alias: App\User\Infrastructure\Firebase\Security\Authenticator\AuthenticateUserFakeFirebase