doctrine_mongodb:
    auto_generate_proxy_classes: true
    auto_generate_hydrator_classes: true
    connections:
        default:
            server: '%env(resolve:MONGODB_URL)%'
            options: {}
    default_database: '%env(resolve:MONGODB_DB)%'
    document_managers:
        default:
            auto_mapping: true
            mappings:
                bottle_inventory:
                    dir: '%kernel.project_dir%/src/BottleInventory/Application/'
                    prefix: 'App\BottleInventory\Application\'
                country:
                    dir: '%kernel.project_dir%/src/Country/Application/'
                    prefix: 'App\Country\Application\'
                security:
                    dir: '%kernel.project_dir%/src/Security/Application/'
                    prefix: 'App\Security\Application\'
                tasting:
                    dir: '%kernel.project_dir%/src/Tasting/Application/'
                    prefix: 'App\Tasting\Application\'

when@prod:
    doctrine_mongodb:
        auto_generate_proxy_classes: false
        auto_generate_hydrator_classes: false
        document_managers:
            default:
                metadata_cache_driver:
                    type: service
                    id: doctrine_mongodb.system_cache_pool

    framework:
        cache:
            pools:
                doctrine_mongodb.system_cache_pool:
                    adapter: cache.system
