doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'
    orm:
        auto_generate_proxy_classes: true
        enable_lazy_ghost_objects: true
        report_fields_where_declared: true
        validate_xml_mapping: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            BottleInventory:
                type: attribute
                is_bundle: false
                dir: '%kernel.project_dir%/src/BottleInventory/Domain/'
                prefix: 'App\BottleInventory\Domain\'
                alias: App
            Country:
                type: attribute
                is_bundle: false
                dir: '%kernel.project_dir%/src/Country/Domain/'
                prefix: 'App\Country\Domain\'
                alias: App
            Security:
                type: attribute
                is_bundle: false
                dir: '%kernel.project_dir%/src/Security/Domain/'
                prefix: 'App\Security\Domain\'
                alias: App

when@test:
    doctrine:
        dbal:
            dbname_suffix: '_test%env(default::TEST_TOKEN)%'

when@prod:
    doctrine:
        orm:
            auto_generate_proxy_classes: false
            proxy_dir: '%kernel.build_dir%/doctrine/orm/Proxies'
            query_cache_driver:
                type: pool
                pool: doctrine.system_cache_pool
            result_cache_driver:
                type: pool
                pool: doctrine.result_cache_pool

    framework:
        cache:
            pools:
                doctrine.result_cache_pool:
                    adapter: cache.app
                doctrine.system_cache_pool:
                    adapter: cache.system
