framework:
    messenger:
        transports:
            sync: 'sync://'
            bottle_inventory:
                dsn: '%env(MESSENGER_TRANSPORT_BOTTLE_INVENTORY_DSN)%'
                options:
                    exchange:
                        name: bottle_inventory
                        type: direct
                        default_publish_routing_key: bottle_inventory
                    queues:
                        bottle_inventory:
                            binding_keys: [ bottle_inventory ]
            bottle_inventory_from_external:
                dsn: '%env(MESSENGER_TRANSPORT_BOTTLE_INVENTORY_DSN)%'
                options:
                    exchange:
                        name: bottle_inventory_from_external
                        type: direct
                        default_publish_routing_key: bottle_inventory_from_external
                    queues:
                        bottle_inventory:
                            binding_keys: [ bottle_inventory_from_external ]
            security:
                dsn: '%env(MESSENGER_TRANSPORT_SECURITY_DSN)%'
                options:
                    exchange:
                        name: security
                        type: direct
                        default_publish_routing_key: security
                    queues:
                        security:
                            binding_keys: [ security ]
            bottle_inventory_to_tasting:
                dsn: '%env(MESSENGER_TRANSPORT_BOTTLE_INVENTORY_TO_TASTING_DSN)%'
                serializer: messenger.transport.symfony_serializer
                options:
                    exchange:
                        name: tasting_from_external
                        type: direct
                        default_publish_routing_key: tasting_from_external
                    queues:
                        tasting:
                            binding_keys: [tasting_from_external]
            tasting:
                dsn: '%env(MESSENGER_TRANSPORT_TASTING_DSN)%'
                options:
                    exchange:
                        name: tasting
                        type: direct
                        default_publish_routing_key: tasting
                    queues:
                        tasting:
                            binding_keys: [tasting]
            tasting_from_external:
                dsn: '%env(MESSENGER_TRANSPORT_TASTING_DSN)%'
                serializer: App\Tasting\Infrastructure\Symfony\Messenger\Serializer\ExternalMessageSerializer
                options:
                    exchange:
                        name: tasting_from_external
                        type: direct
                        default_publish_routing_key: tasting_from_external
                    queues:
                        tasting:
                            binding_keys: [tasting_from_external]
        routing:
            'App\BottleInventory\Infrastructure\Symfony\Messenger\Message\BottleTastedMessage': bottle_inventory_to_tasting

            'App\Tasting\Infrastructure\Symfony\Messenger\Message\InvitationCreatedMessage': tasting
            'App\Tasting\Infrastructure\Symfony\Messenger\Message\InvitationStatusChangedInterface': tasting

when@test:
    framework:
        messenger:
            transports:
                bottle_inventory: 'test://'
                bottle_inventory_from_external:
                    dsn: 'test://'
                    serializer: messenger.transport.native_php_serializer
                security: 'test://'
                bottle_inventory_to_tasting: 'test://'
                tasting: 'test://'
                tasting_from_external:
                    dsn: 'test://'
                    serializer: messenger.transport.native_php_serializer

            routing:
                'App\Tasting\Infrastructure\Symfony\Messenger\ExternalMessage\BottleTastedMessage': tasting_from_external