framework:
    messenger:
        transports:
            sync: 'sync://'
            tasting:
                dsn: '%env(MESSENGER_TRANSPORT_TASTING_DSN)%'
                options:
                    exchange:
                        name: tasting
                        type: direct
                        default_publish_routing_key: tasting
                    queues:
                        tasting:
                            binding_keys: [tasting]
            tasting_from_external:
                dsn: '%env(MESSENGER_TRANSPORT_TASTING_DSN)%'
                serializer: App\Tasting\Infrastructure\Symfony\Messenger\Serializer\ExternalMessageSerializer
                options:
                    exchange:
                        name: tasting_from_external
                        type: direct
                        default_publish_routing_key: tasting_from_external
                    queues:
                        tasting:
                            binding_keys: [tasting_from_external]
        routing:
            'App\Tasting\Infrastructure\Symfony\Messenger\Message\InvitationCreatedMessage': tasting
            'App\Tasting\Infrastructure\Symfony\Messenger\Message\InvitationStatusChangedInterface': tasting
            'App\Tasting\Infrastructure\Symfony\Messenger\Message\CreateSheetWhenInvitationIsAcceptedMessage': tasting
            'App\Tasting\Infrastructure\Symfony\Messenger\Message\CreateSheetWhenTastingIsCreatedMessage': tasting
            'App\Tasting\Infrastructure\Symfony\Messenger\Message\TastingDeletedMessage': tasting

when@test:
    framework:
        messenger:
            transports:
                tasting: 'test://'
                tasting_from_external:
                    dsn: 'test://'
                    serializer: messenger.transport.native_php_serializer

            routing:
                'App\Tasting\Infrastructure\Symfony\Messenger\ExternalMessage\UserCreatedMessage': tasting_from_external
                'App\Tasting\Infrastructure\Symfony\Messenger\ExternalMessage\BottleTastedMessage': tasting_from_external