vich_uploader:
    db_driver: orm
    metadata:
        type: attribute
    mappings:
        bottles:
            uri_prefix: /images/bottle
            upload_destination: '%kernel.project_dir%/public/images/bottle'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
