version: '3'

services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./docker/nginx-proxy/cert/:/etc/nginx/certs/
    networks:
      - web

  php:
    build: ./docker/php
    restart: on-failure
    working_dir: /home/app
    volumes:
      - .:/home/app
      - ./docker/php/Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - web
    tty: true

  db:
    image: mariadb:10.11
    command: --default-authentication-plugin=mysql_native_password
    restart: on-failure
    volumes:
      - .:/home/app
    environment:
      MYSQL_ROOT_PASSWORD: root
    networks:
      - web

  redis:
    image: redis:7.2-alpine
    networks:
      - web

networks:
    web:

volumes:
  caddy_data:
  caddy_config: