parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            $kernelProjectDirectory: '%kernel.project_dir%'

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    DataFixtures\:
        resource: '../fixtures'

    # Bottle
    App\Bottle\Application\EventListener\OnOwnerNotExistEventListener:
        tags: [kernel.event_listener]

    App\Bottle\Application\EventListener\OnBottleUpdateNotAuthorizeEventListener:
        tags: [kernel.event_listener]

    App\Bottle\Domain\Service\UploadBottlePictureServiceInterface:
        alias: App\Bottle\Infrastructure\VichUploader\UploadBottlePictureVichUploaderService

    # Country
    App\Bottle\Infrastructure\Country\Http\Client\CountryHttpClientInterface:
        alias: App\Bottle\Infrastructure\Country\Http\Client\CountryHttpClient

    # User
    App\User\Domain\Service\AuthenticateUserInterface:
        alias: App\User\Infrastructure\Firebase\Security\Authenticator\AuthenticateUserFirebase

    App\User\Application\EventListener\OnCheckOwnerExistEventListener:
        tags: [kernel.event_listener]

    App\User\Application\EventListener\OnCheckIfUserIsAuthorizeToUpdateBottleEventListener:
        tags: [kernel.event_listener]

when@test:
    services:
        # Bottle
        App\Bottle\Infrastructure\Country\Http\Client\CountryHttpClientInterface:
            alias: App\Bottle\Infrastructure\Country\Http\Client\CountryFakeHttpClient

        App\Bottle\Domain\Service\UploadBottlePictureServiceInterface:
            alias: App\Bottle\Infrastructure\VichUploader\UploadBottlePictureVichUploaderTestService

        # User
        App\User\Domain\Service\AuthenticateUserInterface:
            alias: App\User\Infrastructure\Firebase\Security\Authenticator\AuthenticateUserFakeFirebase