services:
  _defaults:
    autowire: true
    autoconfigure: true
    bind:
      $kernelProjectDirectory: '%kernel.project_dir%'
      $emailTastingUserService: '%env(SERVICE_ACCOUNT_TASTING_LOGIN)%'
      $passwordTastingUserService: '%env(SERVICE_ACCOUNT_TASTING_PASSWORD)%'

  App\:
    resource: '../src/'

  DataFixtures\:
    resource: '../fixtures'

  App\Country\Application\Projection\CreateCountryProjection:
    tags: [kernel.event_listener]

  App\Tasting\Application\Projection\CreateTastingProjection:
    tags: [kernel.event_listener]

  App\Tasting\Application\Projection\CreateInvitationProjection:
    tags: [kernel.event_listener]

  App\Tasting\Application\Projection\DeleteInvitationProjection:
    tags: [kernel.event_listener]

  App\Tasting\Infrastructure\Security\Repository\ParticipantRepositoryInterface:
    alias: App\Tasting\Infrastructure\Security\Repository\ParticipantRepository

  App\Country\Application\Adapter\CountryAdapterInterface:
    alias: App\Country\Infrastructure\Doctrine\Adapter\CountryDoctrineAdapter
    public: true

  App\Tasting\Application\Adapter\TastingAdapterInterface:
    alias: App\Tasting\Infrastructure\Doctrine\Adapter\TastingDoctrineAdapter
    public: true

  App\Tasting\Application\Adapter\InvitationAdapterInterface:
    alias: App\Tasting\Infrastructure\Doctrine\Adapter\InvitationDoctrineAdapter
    public: true

  App\Tasting\Application\Service\NotificationInterface:
    alias: App\Tasting\Infrastructure\Firebase\NotificationFirebase
    public: true

  App\Tasting\Application\EventListener\OnInvitationCreated:
    tags: [kernel.event_listener]

  App\Tasting\Application\EventListener\OnInvitationAccepted:
    tags: [kernel.event_listener]

  App\Tasting\Application\EventListener\OnInvitationRejected:
    tags: [kernel.event_listener]

  App\Tasting\Application\EventListener\OnTargetSetFullNameEventOnEachInvitationEventListener:
    tags: [kernel.event_listener]

when@dev:
  services:
    EmpireDesAmis\SecurityAuthenticatorBundle\Firebase\Security\Authenticator\AuthenticateUserFromProviderFirebaseInterface:
      alias: EmpireDesAmis\SecurityAuthenticatorBundle\Firebase\Security\Authenticator\AuthenticateUserFromProviderFakeFirebase

when@test:
  services:
    App\Tasting\Infrastructure\Security\Repository\ParticipantRepositoryInterface:
      alias: App\Tasting\Infrastructure\Security\Repository\ParticipantFakeRepository

    App\Tasting\Application\Service\NotificationInterface:
      alias: App\Tasting\Infrastructure\Firebase\NotificationFirebaseFake
      public: true

    EmpireDesAmis\SecurityAuthenticatorBundle\Firebase\Security\Authenticator\AuthenticateUserFromProviderFirebaseInterface:
      alias: EmpireDesAmis\SecurityAuthenticatorBundle\Firebase\Security\Authenticator\AuthenticateUserFromProviderFakeFirebase
