parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            $kernelProjectDirectory: '%kernel.project_dir%'

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\User\Domain\Service\AuthenticateUserInterface:
        alias: App\User\Infrastructure\Firebase\Security\Authenticator\AuthenticateUser

    DataFixtures\:
        resource: '../fixtures'

when@test:
    services:
        App\User\Domain\Service\AuthenticateUserInterface:
            alias: App\User\Infrastructure\Firebase\Security\Authenticator\AuthenticateUserFake