services:
  _defaults:
    autowire: true
    autoconfigure: true
    bind:
      $emailTastingUserService: '%env(SERVICE_ACCOUNT_TASTING_LOGIN)%'
      $passwordTastingUserService: '%env(SERVICE_ACCOUNT_TASTING_PASSWORD)%'

  App\:
    resource: '../src/'

  DataFixtures\:
    resource: '../fixtures'

  App\Tasting\Application\Projection\CreateTastingProjection:
    tags: [kernel.event_listener]

  App\Tasting\Application\Projection\CreateInvitationProjection:
    tags: [kernel.event_listener]

  App\Tasting\Application\Projection\DeleteInvitationProjection:
    tags: [kernel.event_listener]

  App\Tasting\Application\Projection\CreateSheetProjection:
    tags: [kernel.event_listener]

  App\Tasting\Application\Projection\AddEyeToSheetProjection:
    tags: [kernel.event_listener]

  App\Tasting\Application\Projection\UpdateEyeToSheetProjection:
    tags: [kernel.event_listener]

  App\Tasting\Application\Projection\AddNoseToSheetProjection:
    tags: [kernel.event_listener]

  App\Tasting\Application\Projection\UpdateNoseToSheetProjection:
    tags: [kernel.event_listener]

  App\Tasting\Application\Projection\AddMouthToSheetProjection:
    tags: [kernel.event_listener]

  App\Tasting\Application\Projection\UpdateMouthToSheetProjection:
    tags: [kernel.event_listener]

  App\Tasting\Infrastructure\User\Repository\ParticipantRepositoryInterface:
    alias: App\Tasting\Infrastructure\User\Repository\ParticipantRepository

  App\Tasting\Application\Adapter\TastingAdapterInterface:
    alias: App\Tasting\Infrastructure\Doctrine\Adapter\TastingDoctrineAdapter
    public: true

  App\Tasting\Application\Adapter\InvitationAdapterInterface:
    alias: App\Tasting\Infrastructure\Doctrine\Adapter\InvitationDoctrineAdapter
    public: true

  App\Tasting\Application\Adapter\SheetAdapterInterface:
    alias: App\Tasting\Infrastructure\Doctrine\Adapter\SheetDoctrineAdapter
    public: true

  App\Tasting\Application\Service\NotificationInterface:
    alias: App\Tasting\Infrastructure\Firebase\NotificationFirebase
    public: true

  App\Tasting\Application\EventListener\OnInvitationCreated:
    tags: [kernel.event_listener]

  App\Tasting\Application\EventListener\OnInvitationAccepted:
    tags: [kernel.event_listener]

  App\Tasting\Application\EventListener\OnInvitationRejected:
    tags: [kernel.event_listener]

  App\Tasting\Application\EventListener\OnTargetSetFullNameEventOnEachInvitationEventListener:
    tags: [kernel.event_listener]

  App\Tasting\Application\EventListener\CreateSheetWhenInvitationIsAccepted:
    tags: [kernel.event_listener]

  App\Tasting\Application\EventListener\CreateSheetWhenTastingIsCreated:
    tags: [kernel.event_listener]

when@dev:
  services:
    EmpireDesAmis\SecurityAuthenticatorBundle\Firebase\Security\Authenticator\AuthenticateUserFromProviderFirebaseInterface:
      alias: EmpireDesAmis\SecurityAuthenticatorBundle\Firebase\Security\Authenticator\AuthenticateUserFromProviderFakeFirebase

when@test:
  services:
    App\Tasting\Infrastructure\User\Repository\ParticipantRepositoryInterface:
      alias: App\Tasting\Infrastructure\User\Repository\ParticipantFakeRepository

    App\Tasting\Application\Service\NotificationInterface:
      alias: App\Tasting\Infrastructure\Firebase\NotificationFirebaseFake
      public: true

    EmpireDesAmis\SecurityAuthenticatorBundle\Firebase\Security\Authenticator\AuthenticateUserFromProviderFirebaseInterface:
      alias: EmpireDesAmis\SecurityAuthenticatorBundle\Firebase\Security\Authenticator\AuthenticateUserFromProviderFakeFirebase
